on:
  schedule:
    - cron: '0 0 * * 0'
  push:
  pull_request:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Update Kernel Headers"
        run: ./update_headers.sh
      - name: "Commit Changes"
        run: |
          git add .
          git config --global user.name 'raisinware'
          git config --global user.email 'raisinware@users.noreply.github.com'
          git commit -am "Update Kernel Headers to $(cat .version)"
          git push
